backend:
  name: 'git-gateway'
  branch: 'master'

display_url: 'https://miloandfinn.netlify.com'
logo_url: 'https://miloandfinn.netlify.com/assets/favicons/android-chrome-384x384.png'
media_library:
  name: 'uploadcare'
  config:
    publicKey: '9f0b2b6f1d82d63f1332'
    imagesOnly: true
    tabs: 'file gphotos url'

collections:
  - name: 'pages'
    label: 'Pages'
    description: 'All pages from both English and Indonesian websites'
    editor:
      preview: false
    files:
      - label: 'About Us'
        name: 'about'
        file: 'pages/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Slug', name: 'slug', widget: 'hidden', default: 'about' }
          - { label: 'Tags', name: 'tags', widget: 'hidden', default: 'nav' }
          - { label: 'Summary', name: 'summary', widget: 'text' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Tentang Kami'
        name: 'tentang'
        file: 'pages/id/tentang.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Slug', name: 'slug', widget: 'hidden', default: 'tentang-kami' }
          - { label: 'Tags', name: 'tags', widget: 'hidden', default: 'navId' }
          - { label: 'Lang', name: 'lang', widget: 'hidden', default: 'id' }
          - { label: 'Summary', name: 'summary', widget: 'text' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'FAQ'
        name: 'faq'
        file: 'pages/faq.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Slug', name: 'slug', widget: 'hidden', default: 'faq' }
          - { label: 'Tags', name: 'tags', widget: 'hidden', default: 'nav' }
          - label: 'Questions'
            name: 'questions'
            widget: 'list'
            fields:
              - { label: 'Question', name: 'question', widget: 'string' }
              - { label: 'Answer', name: 'answer', widget: 'text' }

  - name: 'events'
    label: 'Events in English'
    description: 'Add or modify English events here'
    editor:
      preview: false
    folder: 'events'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Date', name: 'date', widget: 'date'}
      - {label: 'Location', name: 'location', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
      - {label: 'Image', name: 'image', widget: 'image', required: false}
      - label: 'Gallery'
        name: 'gallery'
        widget: 'image'
        required: false
        media_library:
          config:
            multiple: true
            previewStep: false

  - name: 'events-id'
    label: 'Events in Indonesian'
    description: 'Add or modify Indonesian events here'
    editor:
      preview: false
    folder: 'events/id'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Date', name: 'date', widget: 'date'}
      - {label: 'Location', name: 'location', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
      - {label: 'Image', name: 'image', widget: 'image', required: false}
      - label: 'Gallery'
        name: 'gallery'
        widget: 'image'
        required: false
        media_library:
          config:
            multiple: true
            previewStep: false
    
  - name: 'settings'
    label: 'Settings'
    description: 'Configure settings for the website here'
    delete: false
    editor:
      preview: false
    files:
      - label: 'Site Settings'
        name: 'settings'
        file: 'config/config.json'
        fields:
          - label: 'General'
            name: 'site'
            widget: 'object'
            fields:
              - { label: 'Site Name', name: 'name', widget: 'string'}
              - { label: 'Home URL', name: 'url', widget: 'string', hint: 'Must starts with https://'}
              - { label: 'Default Language', name: 'lang', widget: 'string'}
              - { label: 'Summary', name: 'summary', widget: 'string'}
              - { label: 'Description', name: 'description', widget: 'text', hint: 'Must not exceed 160 characters' }
              - { label: 'Admin Email', name: 'webmaster', widget: 'string' }
              - { label: 'Theme Color', name: 'themeColor', widget: 'string', hint: 'Hex value of a color. For example, #ffffff'}
          - label: 'Locales'
            name: 'locales'
            widget: 'object'
            fields: 
              - label: 'English'
                name: 'en'
                widget: 'object'
                fields: 
                  - { label: 'URL', name: 'url', widget: 'string' }
                  - { label: 'next', name: 'next', widget: 'string' }
              - label: 'Indonesian'
                name: 'id'
                widget: 'object'
                fields: 
                  - { label: 'URL', name: 'url', widget: 'string' }
                  - { label: 'next', name: 'next', widget: 'string' }
          - label: 'Social'
            name: 'social'
            widget: 'object'
            fields:
              - { label: 'Facebook Page', name: 'facebook', widget: 'string', required: false }
              - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
              - { label: 'Instagram', name: 'instagram', widget: 'string', required: false }
          - label: 'Analytics'
            name: 'analytics'
            widget: 'object'
            fields:
              - { label: 'Google Tracking ID', name: 'google', widget: 'string', required: false, hint: 'Starts with GTM- ...' }
              - { label: 'Twitter Handle', name: 'twitter', widget: 'string', required: false }
              - { label: 'Facebook App ID', name: 'facebook', widget: 'string', required: false }
          - label: 'Form'
            name: 'form'
            widget: 'object'
            fields:
              - { label: 'Form Name', name: 'name', widget: 'string', hint: 'What the form is called in Netlify (Capitalize first letter)' }
          - label: 'Fallback Images'
            name: 'fallback'
            widget: 'object'
            fields:
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }